version: '3.9'

services:
  db:
    container_name: 'db'
    image: mysql:8.1
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      MSQL_TCP_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - local

volumes:
  mysql_data:

networks:
  local:
    driver: bridge