version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15.0-alpine
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_SCHEMA: public
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - local

  app:
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c 'java -jar /app/target/*.jar'
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${DB_DATABASE}?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_FLYWAY_URL: jdbc:postgresql://db:${DB_PORT}/${DB_DATABASE}?stringtype=unspecified
      SPRING_FLYWAY_USER: ${DB_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - local

volumes:
  db_data:

networks:
  local:
    driver: bridge