version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15.0-alpine
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_SCHEMA: public
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - local

  app:
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c 'java -jar /app/target/*.jar'
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${DB_DATABASE}?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_FLYWAY_URL: jdbc:postgresql://db:${DB_PORT}/${DB_DATABASE}?stringtype=unspecified
      SPRING_FLYWAY_USER: ${DB_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - local

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - local
    depends_on:
      - app

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - local
    depends_on:
      - prometheus

  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    ports:
      - '9000:9000'
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:${DB_PORT}/sonar
      SONAR_JDBC_USERNAME: ${DB_USER}
      SONAR_JDBC_PASSWORD: ${DB_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - db
    networks:
      - local

volumes:
  db_data:
  prometheus_data:
  grafana_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  local:
    driver: bridge