CREATE TABLE IF NOT EXISTS cards(
    id CHAR(36) PRIMARY KEY,
    number VARCHAR(255) NOT NULL UNIQUE,
    owner VARCHAR(150) NOT NULL,
    validity CHAR(5) NOT NULL,
    cvv VARCHAR(255) NOT NULL
);